name: Unit testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup C++
  # You may pin to the exact commit or the version.
  # uses: Trass3r/setup-cpp@5483836ab5de3434caf3ab7d5d1fc19f0fa206f9
  uses: Trass3r/setup-cpp@v1
      
    - name: install math library
      run:  sudo apt-get install -y libmath-libm-perl 
      
    - name: make test
      run:  make test
